"""grupo_familiar_admin

Revision ID: 45bf21351967
Revises: b0cef958fc44
Create Date: 2024-02-05 14:55:55.584426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45bf21351967'
down_revision = 'b0cef958fc44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupos_familiares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_admin', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'usuarios', ['id_admin'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_confirmacion_grupo', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('fecha_confirmacion_grupo')

    with op.batch_alter_table('grupos_familiares', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_admin')

    # ### end Alembic commands ###
