"""migracion inicial

Revision ID: b0cef958fc44
Revises: 
Create Date: 2024-02-05 12:33:59.810412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0cef958fc44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos_familiares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_familia', sa.String(length=50), nullable=False),
    sa.Column('imagen_grupo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_familia')
    )
    op.create_table('provincias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_en_lista',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ciudades',
    sa.Column('cod_postal', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id_provincia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_provincia'], ['provincias.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cod_postal')
    )
    op.create_table('supermercados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('cod_postal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cod_postal'], ['ciudades.cod_postal'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('telefono', sa.String(length=12), nullable=False),
    sa.Column('imagen_perfil', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('id_grupo_familiar', sa.Integer(), nullable=True),
    sa.Column('cod_postal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cod_postal'], ['ciudades.cod_postal'], ),
    sa.ForeignKeyConstraint(['id_grupo_familiar'], ['grupos_familiares.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('listas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('id_autor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_autor'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_roles',
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE')
    )
    op.create_table('compras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_compra', sa.DateTime(), nullable=True),
    sa.Column('id_comprador', sa.Integer(), nullable=True),
    sa.Column('id_lista', sa.Integer(), nullable=False),
    sa.Column('id_supermercado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_comprador'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_lista'], ['listas.id'], ),
    sa.ForeignKeyConstraint(['id_supermercado'], ['supermercados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_listas',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lista_id'], ['listas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles_en_lista.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'lista_id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('esta_en_carrito', sa.Boolean(), nullable=True),
    sa.Column('id_lista', sa.Integer(), nullable=True),
    sa.Column('id_compra', sa.Integer(), nullable=True),
    sa.Column('id_autor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_autor'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['id_lista'], ['listas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    op.drop_table('usuarios_listas')
    op.drop_table('compras')
    op.drop_table('usuarios_roles')
    op.drop_table('listas')
    op.drop_table('usuarios')
    op.drop_table('supermercados')
    op.drop_table('ciudades')
    op.drop_table('roles_en_lista')
    op.drop_table('roles')
    op.drop_table('provincias')
    op.drop_table('grupos_familiares')
    # ### end Alembic commands ###
