"""actualizacion_largo_imagenes

Revision ID: b64825e13094
Revises: 45bf21351967
Create Date: 2024-02-05 18:09:48.538276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b64825e13094'
down_revision = '45bf21351967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupos_familiares', schema=None) as batch_op:
        batch_op.alter_column('imagen_grupo',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=25),
               existing_nullable=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('imagen_perfil',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('imagen_perfil',
               existing_type=sa.String(length=25),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('grupos_familiares', schema=None) as batch_op:
        batch_op.alter_column('imagen_grupo',
               existing_type=sa.String(length=25),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
